


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "drizzle";


ALTER SCHEMA "drizzle" OWNER TO "postgres";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "drizzle"."__drizzle_migrations" (
    "id" integer NOT NULL,
    "hash" "text" NOT NULL,
    "created_at" bigint
);


ALTER TABLE "drizzle"."__drizzle_migrations" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "drizzle"."__drizzle_migrations_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "drizzle"."__drizzle_migrations_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "drizzle"."__drizzle_migrations_id_seq" OWNED BY "drizzle"."__drizzle_migrations"."id";



CREATE TABLE IF NOT EXISTS "public"."assetFloor" (
    "id" bigint NOT NULL,
    "name" "text",
    "created_at" timestamp with time zone
);


ALTER TABLE "public"."assetFloor" OWNER TO "postgres";


COMMENT ON TABLE "public"."assetFloor" IS 'Floor location of an asset';



ALTER TABLE "public"."assetFloor" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."assetFloor_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."assetRoom" (
    "id" bigint NOT NULL,
    "name" "text",
    "created_at" timestamp with time zone
);


ALTER TABLE "public"."assetRoom" OWNER TO "postgres";


COMMENT ON TABLE "public"."assetRoom" IS 'Asset room location';



ALTER TABLE "public"."assetRoom" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."assetRoom_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."assetStatusHistory" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "assetId" "uuid" NOT NULL,
    "status" "text" NOT NULL,
    "remarks" "text" NOT NULL,
    "updatedBy" "uuid" NOT NULL,
    "updatedAt" timestamp with time zone
);


ALTER TABLE "public"."assetStatusHistory" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."assetType" (
    "id" bigint NOT NULL,
    "name" "text",
    "created_at" timestamp with time zone
);


ALTER TABLE "public"."assetType" OWNER TO "postgres";


COMMENT ON TABLE "public"."assetType" IS 'Table for inserting the asset type name';



ALTER TABLE "public"."assetType" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."assetType_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."assets" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "assetName" "text" NOT NULL,
    "assetType" bigint,
    "serialNumber" "text" NOT NULL,
    "specification" "text" NOT NULL,
    "currentStatus" "text" NOT NULL,
    "createdAt" timestamp without time zone,
    "isAssigned" boolean DEFAULT false,
    "room" bigint,
    "floor" bigint,
    "tag" "text" NOT NULL,
    "image" "jsonb"
);


ALTER TABLE "public"."assets" OWNER TO "postgres";


COMMENT ON COLUMN "public"."assets"."tag" IS 'Asset tag';



CREATE TABLE IF NOT EXISTS "public"."assetsAssignment" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "userId" "uuid" NOT NULL,
    "assignedDate" timestamp without time zone,
    "returnedDate" timestamp without time zone,
    "acknowledged" boolean DEFAULT false NOT NULL,
    "assetId" "uuid"
);


ALTER TABLE "public"."assetsAssignment" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."asssetStatusHistory" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "assetId" "uuid" NOT NULL,
    "status" "text" NOT NULL,
    "remarks" "text" NOT NULL,
    "updatedBy" "uuid" NOT NULL,
    "updatedAt" timestamp without time zone
);


ALTER TABLE "public"."asssetStatusHistory" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."issueReports" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "assetId" "uuid" NOT NULL,
    "reportedBy" "uuid" NOT NULL,
    "description" "text" NOT NULL,
    "status" "text" NOT NULL,
    "reportAt" timestamp without time zone
);


ALTER TABLE "public"."issueReports" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."qrCodes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "assetId" "uuid" NOT NULL,
    "qrValue" "text" NOT NULL,
    "generateAt" timestamp without time zone
);


ALTER TABLE "public"."qrCodes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."roles" (
    "id" bigint NOT NULL,
    "roleName" "text"
);


ALTER TABLE "public"."roles" OWNER TO "postgres";


ALTER TABLE "public"."roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."roles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "email" "text" NOT NULL,
    "fullName" "text" NOT NULL,
    "password" "text" NOT NULL,
    "department" "text" NOT NULL,
    "createdAt" timestamp without time zone,
    "roleId" smallint NOT NULL,
    "phoneNumber" "text",
    "status" "text" DEFAULT 'active'::"text" NOT NULL,
    "lastActive" timestamp with time zone,
    "assetCount" bigint,
    "assetsCount" bigint DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE ONLY "drizzle"."__drizzle_migrations" ALTER COLUMN "id" SET DEFAULT "nextval"('"drizzle"."__drizzle_migrations_id_seq"'::"regclass");



ALTER TABLE ONLY "drizzle"."__drizzle_migrations"
    ADD CONSTRAINT "__drizzle_migrations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."assetFloor"
    ADD CONSTRAINT "assetFloor_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."assetRoom"
    ADD CONSTRAINT "assetRoom_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."assetStatusHistory"
    ADD CONSTRAINT "assetStatusHistory_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."assetType"
    ADD CONSTRAINT "assetType_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."assetsAssignment"
    ADD CONSTRAINT "assetsAssignment_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."assets"
    ADD CONSTRAINT "assets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."asssetStatusHistory"
    ADD CONSTRAINT "asssetStatusHistory_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."issueReports"
    ADD CONSTRAINT "issueReports_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."qrCodes"
    ADD CONSTRAINT "qrCodes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_unique" UNIQUE ("email");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



CREATE UNIQUE INDEX "idx_qrCodes_asset_id" ON "public"."qrCodes" USING "btree" ("assetId");



ALTER TABLE ONLY "public"."assetsAssignment"
    ADD CONSTRAINT "assetsAssignment_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "public"."assets"("id");



ALTER TABLE ONLY "public"."assetsAssignment"
    ADD CONSTRAINT "assetsAssignment_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."assets"
    ADD CONSTRAINT "assets_assetType_fkey" FOREIGN KEY ("assetType") REFERENCES "public"."assetType"("id");



ALTER TABLE ONLY "public"."assets"
    ADD CONSTRAINT "assets_floor_fkey" FOREIGN KEY ("floor") REFERENCES "public"."assetFloor"("id");



ALTER TABLE ONLY "public"."assets"
    ADD CONSTRAINT "assets_room_fkey" FOREIGN KEY ("room") REFERENCES "public"."assetRoom"("id");



ALTER TABLE ONLY "public"."asssetStatusHistory"
    ADD CONSTRAINT "asssetStatusHistory_assetId_assets_id_fk" FOREIGN KEY ("assetId") REFERENCES "public"."assets"("id");



ALTER TABLE ONLY "public"."asssetStatusHistory"
    ADD CONSTRAINT "asssetStatusHistory_updatedBy_users_id_fk" FOREIGN KEY ("updatedBy") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."assets"
    ADD CONSTRAINT "fk_assets_asset_type_rel" FOREIGN KEY ("assetType") REFERENCES "public"."assetType"("id");



ALTER TABLE ONLY "public"."assets"
    ADD CONSTRAINT "fk_assets_floor_rel" FOREIGN KEY ("floor") REFERENCES "public"."assetFloor"("id");



ALTER TABLE ONLY "public"."assets"
    ADD CONSTRAINT "fk_assets_room_rel" FOREIGN KEY ("room") REFERENCES "public"."assetRoom"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "fk_users_role" FOREIGN KEY ("roleId") REFERENCES "public"."roles"("id");



ALTER TABLE ONLY "public"."issueReports"
    ADD CONSTRAINT "issueReports_assetId_assets_id_fk" FOREIGN KEY ("assetId") REFERENCES "public"."assets"("id");



ALTER TABLE ONLY "public"."issueReports"
    ADD CONSTRAINT "issueReports_reportedBy_users_id_fk" FOREIGN KEY ("reportedBy") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."qrCodes"
    ADD CONSTRAINT "qrCodes_assetId_assets_id_fk" FOREIGN KEY ("assetId") REFERENCES "public"."assets"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "public"."roles"("id");



ALTER TABLE "public"."assetFloor" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."assetRoom" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."assetType" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."assetFloor" TO "anon";
GRANT ALL ON TABLE "public"."assetFloor" TO "authenticated";
GRANT ALL ON TABLE "public"."assetFloor" TO "service_role";



GRANT ALL ON SEQUENCE "public"."assetFloor_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."assetFloor_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."assetFloor_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."assetRoom" TO "anon";
GRANT ALL ON TABLE "public"."assetRoom" TO "authenticated";
GRANT ALL ON TABLE "public"."assetRoom" TO "service_role";



GRANT ALL ON SEQUENCE "public"."assetRoom_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."assetRoom_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."assetRoom_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."assetStatusHistory" TO "anon";
GRANT ALL ON TABLE "public"."assetStatusHistory" TO "authenticated";
GRANT ALL ON TABLE "public"."assetStatusHistory" TO "service_role";



GRANT ALL ON TABLE "public"."assetType" TO "anon";
GRANT ALL ON TABLE "public"."assetType" TO "authenticated";
GRANT ALL ON TABLE "public"."assetType" TO "service_role";



GRANT ALL ON SEQUENCE "public"."assetType_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."assetType_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."assetType_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."assets" TO "anon";
GRANT ALL ON TABLE "public"."assets" TO "authenticated";
GRANT ALL ON TABLE "public"."assets" TO "service_role";



GRANT ALL ON TABLE "public"."assetsAssignment" TO "anon";
GRANT ALL ON TABLE "public"."assetsAssignment" TO "authenticated";
GRANT ALL ON TABLE "public"."assetsAssignment" TO "service_role";



GRANT ALL ON TABLE "public"."asssetStatusHistory" TO "anon";
GRANT ALL ON TABLE "public"."asssetStatusHistory" TO "authenticated";
GRANT ALL ON TABLE "public"."asssetStatusHistory" TO "service_role";



GRANT ALL ON TABLE "public"."issueReports" TO "anon";
GRANT ALL ON TABLE "public"."issueReports" TO "authenticated";
GRANT ALL ON TABLE "public"."issueReports" TO "service_role";



GRANT ALL ON TABLE "public"."qrCodes" TO "anon";
GRANT ALL ON TABLE "public"."qrCodes" TO "authenticated";
GRANT ALL ON TABLE "public"."qrCodes" TO "service_role";



GRANT ALL ON TABLE "public"."roles" TO "anon";
GRANT ALL ON TABLE "public"."roles" TO "authenticated";
GRANT ALL ON TABLE "public"."roles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


  create policy "API Upload Access"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'asset'::text));



  create policy "Auth Upload Access"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'asset'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Public Access"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'asset'::text));



  create policy "Public Image Access"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'asset'::text));



