alter table "public"."assetsAssignment" drop constraint "assetsAssignment_assetId_assets_id_fk";


  create table "public"."assetFloor" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "created_at" timestamp with time zone
      );


alter table "public"."assetFloor" enable row level security;


  create table "public"."assetRoom" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "created_at" timestamp with time zone
      );


alter table "public"."assetRoom" enable row level security;

alter table "public"."assetType" alter column "created_at" drop default;

alter table "public"."assetType" alter column "created_at" drop not null;

alter table "public"."assets" drop column "location";

alter table "public"."assets" add column "floor" bigint;

alter table "public"."assets" add column "image" jsonb;

alter table "public"."assets" add column "room" bigint;

alter table "public"."assets" add column "tag" text not null;

alter table "public"."assetsAssignment" alter column "assetId" drop not null;

CREATE UNIQUE INDEX "assetFloor_pkey" ON public."assetFloor" USING btree (id);

CREATE UNIQUE INDEX "assetRoom_pkey" ON public."assetRoom" USING btree (id);

alter table "public"."assetFloor" add constraint "assetFloor_pkey" PRIMARY KEY using index "assetFloor_pkey";

alter table "public"."assetRoom" add constraint "assetRoom_pkey" PRIMARY KEY using index "assetRoom_pkey";

alter table "public"."assets" add constraint "assets_floor_fkey" FOREIGN KEY (floor) REFERENCES public."assetFloor"(id) not valid;

alter table "public"."assets" validate constraint "assets_floor_fkey";

alter table "public"."assets" add constraint "assets_room_fkey" FOREIGN KEY (room) REFERENCES public."assetRoom"(id) not valid;

alter table "public"."assets" validate constraint "assets_room_fkey";

alter table "public"."assets" add constraint "fk_assets_floor_rel" FOREIGN KEY (floor) REFERENCES public."assetFloor"(id) not valid;

alter table "public"."assets" validate constraint "fk_assets_floor_rel";

alter table "public"."assets" add constraint "fk_assets_room_rel" FOREIGN KEY (room) REFERENCES public."assetRoom"(id) not valid;

alter table "public"."assets" validate constraint "fk_assets_room_rel";

alter table "public"."assetsAssignment" add constraint "assetsAssignment_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES public.assets(id) not valid;

alter table "public"."assetsAssignment" validate constraint "assetsAssignment_assetId_fkey";

grant delete on table "public"."assetFloor" to "anon";

grant insert on table "public"."assetFloor" to "anon";

grant references on table "public"."assetFloor" to "anon";

grant select on table "public"."assetFloor" to "anon";

grant trigger on table "public"."assetFloor" to "anon";

grant truncate on table "public"."assetFloor" to "anon";

grant update on table "public"."assetFloor" to "anon";

grant delete on table "public"."assetFloor" to "authenticated";

grant insert on table "public"."assetFloor" to "authenticated";

grant references on table "public"."assetFloor" to "authenticated";

grant select on table "public"."assetFloor" to "authenticated";

grant trigger on table "public"."assetFloor" to "authenticated";

grant truncate on table "public"."assetFloor" to "authenticated";

grant update on table "public"."assetFloor" to "authenticated";

grant delete on table "public"."assetFloor" to "service_role";

grant insert on table "public"."assetFloor" to "service_role";

grant references on table "public"."assetFloor" to "service_role";

grant select on table "public"."assetFloor" to "service_role";

grant trigger on table "public"."assetFloor" to "service_role";

grant truncate on table "public"."assetFloor" to "service_role";

grant update on table "public"."assetFloor" to "service_role";

grant delete on table "public"."assetRoom" to "anon";

grant insert on table "public"."assetRoom" to "anon";

grant references on table "public"."assetRoom" to "anon";

grant select on table "public"."assetRoom" to "anon";

grant trigger on table "public"."assetRoom" to "anon";

grant truncate on table "public"."assetRoom" to "anon";

grant update on table "public"."assetRoom" to "anon";

grant delete on table "public"."assetRoom" to "authenticated";

grant insert on table "public"."assetRoom" to "authenticated";

grant references on table "public"."assetRoom" to "authenticated";

grant select on table "public"."assetRoom" to "authenticated";

grant trigger on table "public"."assetRoom" to "authenticated";

grant truncate on table "public"."assetRoom" to "authenticated";

grant update on table "public"."assetRoom" to "authenticated";

grant delete on table "public"."assetRoom" to "service_role";

grant insert on table "public"."assetRoom" to "service_role";

grant references on table "public"."assetRoom" to "service_role";

grant select on table "public"."assetRoom" to "service_role";

grant trigger on table "public"."assetRoom" to "service_role";

grant truncate on table "public"."assetRoom" to "service_role";

grant update on table "public"."assetRoom" to "service_role";


  create policy "API Upload Access"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'asset'::text));



  create policy "Auth Upload Access"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'asset'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Public Access"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'asset'::text));



  create policy "Public Image Access"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'asset'::text));



