drop extension if exists "pg_net";

create schema if not exists "drizzle";

create sequence "drizzle"."__drizzle_migrations_id_seq";


  create table "drizzle"."__drizzle_migrations" (
    "id" integer not null default nextval('drizzle.__drizzle_migrations_id_seq'::regclass),
    "hash" text not null,
    "created_at" bigint
      );



  create table "public"."assetStatusHistory" (
    "id" uuid not null default gen_random_uuid(),
    "assetId" uuid not null,
    "status" text not null,
    "remarks" text not null,
    "updatedBy" uuid not null,
    "updatedAt" timestamp with time zone
      );



  create table "public"."assetType" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."assetType" enable row level security;


  create table "public"."assets" (
    "id" uuid not null default gen_random_uuid(),
    "assetName" text not null,
    "assetType" bigint,
    "serialNumber" text not null,
    "specification" text not null,
    "location" text not null,
    "currentStatus" text not null,
    "createdAt" timestamp without time zone,
    "isAssigned" boolean default false
      );



  create table "public"."assetsAssignment" (
    "id" uuid not null default gen_random_uuid(),
    "assetId" uuid not null,
    "userId" uuid not null,
    "assignedDate" timestamp without time zone,
    "returnedDate" timestamp without time zone,
    "acknowledged" boolean not null default false
      );



  create table "public"."asssetStatusHistory" (
    "id" uuid not null default gen_random_uuid(),
    "assetId" uuid not null,
    "status" text not null,
    "remarks" text not null,
    "updatedBy" uuid not null,
    "updatedAt" timestamp without time zone
      );



  create table "public"."issueReports" (
    "id" uuid not null default gen_random_uuid(),
    "assetId" uuid not null,
    "reportedBy" uuid not null,
    "description" text not null,
    "status" text not null,
    "reportAt" timestamp without time zone
      );



  create table "public"."qrCodes" (
    "id" uuid not null default gen_random_uuid(),
    "assetId" uuid not null,
    "qrValue" text not null,
    "generateAt" timestamp without time zone
      );



  create table "public"."roles" (
    "id" bigint generated by default as identity not null,
    "roleName" text
      );



  create table "public"."users" (
    "id" uuid not null default gen_random_uuid(),
    "email" text not null,
    "fullName" text not null,
    "password" text not null,
    "department" text not null,
    "createdAt" timestamp without time zone,
    "roleId" smallint not null,
    "phoneNumber" text,
    "status" text not null default 'active'::text,
    "lastActive" timestamp with time zone,
    "assetCount" bigint,
    "assetsCount" bigint not null default 0
      );


alter sequence "drizzle"."__drizzle_migrations_id_seq" owned by "drizzle"."__drizzle_migrations"."id";

CREATE UNIQUE INDEX __drizzle_migrations_pkey ON drizzle.__drizzle_migrations USING btree (id);

CREATE UNIQUE INDEX "assetStatusHistory_pkey" ON public."assetStatusHistory" USING btree (id);

CREATE UNIQUE INDEX "assetType_pkey" ON public."assetType" USING btree (id);

CREATE UNIQUE INDEX "assetsAssignment_pkey" ON public."assetsAssignment" USING btree (id);

CREATE UNIQUE INDEX assets_pkey ON public.assets USING btree (id);

CREATE UNIQUE INDEX "asssetStatusHistory_pkey" ON public."asssetStatusHistory" USING btree (id);

CREATE UNIQUE INDEX "idx_qrCodes_asset_id" ON public."qrCodes" USING btree ("assetId");

CREATE UNIQUE INDEX "issueReports_pkey" ON public."issueReports" USING btree (id);

CREATE UNIQUE INDEX "qrCodes_pkey" ON public."qrCodes" USING btree (id);

CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (id);

CREATE UNIQUE INDEX users_email_unique ON public.users USING btree (email);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "drizzle"."__drizzle_migrations" add constraint "__drizzle_migrations_pkey" PRIMARY KEY using index "__drizzle_migrations_pkey";

alter table "public"."assetStatusHistory" add constraint "assetStatusHistory_pkey" PRIMARY KEY using index "assetStatusHistory_pkey";

alter table "public"."assetType" add constraint "assetType_pkey" PRIMARY KEY using index "assetType_pkey";

alter table "public"."assets" add constraint "assets_pkey" PRIMARY KEY using index "assets_pkey";

alter table "public"."assetsAssignment" add constraint "assetsAssignment_pkey" PRIMARY KEY using index "assetsAssignment_pkey";

alter table "public"."asssetStatusHistory" add constraint "asssetStatusHistory_pkey" PRIMARY KEY using index "asssetStatusHistory_pkey";

alter table "public"."issueReports" add constraint "issueReports_pkey" PRIMARY KEY using index "issueReports_pkey";

alter table "public"."qrCodes" add constraint "qrCodes_pkey" PRIMARY KEY using index "qrCodes_pkey";

alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."assets" add constraint "assets_assetType_fkey" FOREIGN KEY ("assetType") REFERENCES public."assetType"(id) not valid;

alter table "public"."assets" validate constraint "assets_assetType_fkey";

alter table "public"."assets" add constraint "fk_assets_asset_type_rel" FOREIGN KEY ("assetType") REFERENCES public."assetType"(id) not valid;

alter table "public"."assets" validate constraint "fk_assets_asset_type_rel";

alter table "public"."assetsAssignment" add constraint "assetsAssignment_assetId_assets_id_fk" FOREIGN KEY ("assetId") REFERENCES public.assets(id) not valid;

alter table "public"."assetsAssignment" validate constraint "assetsAssignment_assetId_assets_id_fk";

alter table "public"."assetsAssignment" add constraint "assetsAssignment_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES public.users(id) not valid;

alter table "public"."assetsAssignment" validate constraint "assetsAssignment_userId_users_id_fk";

alter table "public"."asssetStatusHistory" add constraint "asssetStatusHistory_assetId_assets_id_fk" FOREIGN KEY ("assetId") REFERENCES public.assets(id) not valid;

alter table "public"."asssetStatusHistory" validate constraint "asssetStatusHistory_assetId_assets_id_fk";

alter table "public"."asssetStatusHistory" add constraint "asssetStatusHistory_updatedBy_users_id_fk" FOREIGN KEY ("updatedBy") REFERENCES public.users(id) not valid;

alter table "public"."asssetStatusHistory" validate constraint "asssetStatusHistory_updatedBy_users_id_fk";

alter table "public"."issueReports" add constraint "issueReports_assetId_assets_id_fk" FOREIGN KEY ("assetId") REFERENCES public.assets(id) not valid;

alter table "public"."issueReports" validate constraint "issueReports_assetId_assets_id_fk";

alter table "public"."issueReports" add constraint "issueReports_reportedBy_users_id_fk" FOREIGN KEY ("reportedBy") REFERENCES public.users(id) not valid;

alter table "public"."issueReports" validate constraint "issueReports_reportedBy_users_id_fk";

alter table "public"."qrCodes" add constraint "qrCodes_assetId_assets_id_fk" FOREIGN KEY ("assetId") REFERENCES public.assets(id) not valid;

alter table "public"."qrCodes" validate constraint "qrCodes_assetId_assets_id_fk";

alter table "public"."users" add constraint "fk_users_role" FOREIGN KEY ("roleId") REFERENCES public.roles(id) not valid;

alter table "public"."users" validate constraint "fk_users_role";

alter table "public"."users" add constraint "users_email_unique" UNIQUE using index "users_email_unique";

alter table "public"."users" add constraint "users_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES public.roles(id) not valid;

alter table "public"."users" validate constraint "users_roleId_fkey";

grant delete on table "public"."assetStatusHistory" to "anon";

grant insert on table "public"."assetStatusHistory" to "anon";

grant references on table "public"."assetStatusHistory" to "anon";

grant select on table "public"."assetStatusHistory" to "anon";

grant trigger on table "public"."assetStatusHistory" to "anon";

grant truncate on table "public"."assetStatusHistory" to "anon";

grant update on table "public"."assetStatusHistory" to "anon";

grant delete on table "public"."assetStatusHistory" to "authenticated";

grant insert on table "public"."assetStatusHistory" to "authenticated";

grant references on table "public"."assetStatusHistory" to "authenticated";

grant select on table "public"."assetStatusHistory" to "authenticated";

grant trigger on table "public"."assetStatusHistory" to "authenticated";

grant truncate on table "public"."assetStatusHistory" to "authenticated";

grant update on table "public"."assetStatusHistory" to "authenticated";

grant delete on table "public"."assetStatusHistory" to "service_role";

grant insert on table "public"."assetStatusHistory" to "service_role";

grant references on table "public"."assetStatusHistory" to "service_role";

grant select on table "public"."assetStatusHistory" to "service_role";

grant trigger on table "public"."assetStatusHistory" to "service_role";

grant truncate on table "public"."assetStatusHistory" to "service_role";

grant update on table "public"."assetStatusHistory" to "service_role";

grant delete on table "public"."assetType" to "anon";

grant insert on table "public"."assetType" to "anon";

grant references on table "public"."assetType" to "anon";

grant select on table "public"."assetType" to "anon";

grant trigger on table "public"."assetType" to "anon";

grant truncate on table "public"."assetType" to "anon";

grant update on table "public"."assetType" to "anon";

grant delete on table "public"."assetType" to "authenticated";

grant insert on table "public"."assetType" to "authenticated";

grant references on table "public"."assetType" to "authenticated";

grant select on table "public"."assetType" to "authenticated";

grant trigger on table "public"."assetType" to "authenticated";

grant truncate on table "public"."assetType" to "authenticated";

grant update on table "public"."assetType" to "authenticated";

grant delete on table "public"."assetType" to "service_role";

grant insert on table "public"."assetType" to "service_role";

grant references on table "public"."assetType" to "service_role";

grant select on table "public"."assetType" to "service_role";

grant trigger on table "public"."assetType" to "service_role";

grant truncate on table "public"."assetType" to "service_role";

grant update on table "public"."assetType" to "service_role";

grant delete on table "public"."assets" to "anon";

grant insert on table "public"."assets" to "anon";

grant references on table "public"."assets" to "anon";

grant select on table "public"."assets" to "anon";

grant trigger on table "public"."assets" to "anon";

grant truncate on table "public"."assets" to "anon";

grant update on table "public"."assets" to "anon";

grant delete on table "public"."assets" to "authenticated";

grant insert on table "public"."assets" to "authenticated";

grant references on table "public"."assets" to "authenticated";

grant select on table "public"."assets" to "authenticated";

grant trigger on table "public"."assets" to "authenticated";

grant truncate on table "public"."assets" to "authenticated";

grant update on table "public"."assets" to "authenticated";

grant delete on table "public"."assets" to "service_role";

grant insert on table "public"."assets" to "service_role";

grant references on table "public"."assets" to "service_role";

grant select on table "public"."assets" to "service_role";

grant trigger on table "public"."assets" to "service_role";

grant truncate on table "public"."assets" to "service_role";

grant update on table "public"."assets" to "service_role";

grant delete on table "public"."assetsAssignment" to "anon";

grant insert on table "public"."assetsAssignment" to "anon";

grant references on table "public"."assetsAssignment" to "anon";

grant select on table "public"."assetsAssignment" to "anon";

grant trigger on table "public"."assetsAssignment" to "anon";

grant truncate on table "public"."assetsAssignment" to "anon";

grant update on table "public"."assetsAssignment" to "anon";

grant delete on table "public"."assetsAssignment" to "authenticated";

grant insert on table "public"."assetsAssignment" to "authenticated";

grant references on table "public"."assetsAssignment" to "authenticated";

grant select on table "public"."assetsAssignment" to "authenticated";

grant trigger on table "public"."assetsAssignment" to "authenticated";

grant truncate on table "public"."assetsAssignment" to "authenticated";

grant update on table "public"."assetsAssignment" to "authenticated";

grant delete on table "public"."assetsAssignment" to "service_role";

grant insert on table "public"."assetsAssignment" to "service_role";

grant references on table "public"."assetsAssignment" to "service_role";

grant select on table "public"."assetsAssignment" to "service_role";

grant trigger on table "public"."assetsAssignment" to "service_role";

grant truncate on table "public"."assetsAssignment" to "service_role";

grant update on table "public"."assetsAssignment" to "service_role";

grant delete on table "public"."asssetStatusHistory" to "anon";

grant insert on table "public"."asssetStatusHistory" to "anon";

grant references on table "public"."asssetStatusHistory" to "anon";

grant select on table "public"."asssetStatusHistory" to "anon";

grant trigger on table "public"."asssetStatusHistory" to "anon";

grant truncate on table "public"."asssetStatusHistory" to "anon";

grant update on table "public"."asssetStatusHistory" to "anon";

grant delete on table "public"."asssetStatusHistory" to "authenticated";

grant insert on table "public"."asssetStatusHistory" to "authenticated";

grant references on table "public"."asssetStatusHistory" to "authenticated";

grant select on table "public"."asssetStatusHistory" to "authenticated";

grant trigger on table "public"."asssetStatusHistory" to "authenticated";

grant truncate on table "public"."asssetStatusHistory" to "authenticated";

grant update on table "public"."asssetStatusHistory" to "authenticated";

grant delete on table "public"."asssetStatusHistory" to "service_role";

grant insert on table "public"."asssetStatusHistory" to "service_role";

grant references on table "public"."asssetStatusHistory" to "service_role";

grant select on table "public"."asssetStatusHistory" to "service_role";

grant trigger on table "public"."asssetStatusHistory" to "service_role";

grant truncate on table "public"."asssetStatusHistory" to "service_role";

grant update on table "public"."asssetStatusHistory" to "service_role";

grant delete on table "public"."issueReports" to "anon";

grant insert on table "public"."issueReports" to "anon";

grant references on table "public"."issueReports" to "anon";

grant select on table "public"."issueReports" to "anon";

grant trigger on table "public"."issueReports" to "anon";

grant truncate on table "public"."issueReports" to "anon";

grant update on table "public"."issueReports" to "anon";

grant delete on table "public"."issueReports" to "authenticated";

grant insert on table "public"."issueReports" to "authenticated";

grant references on table "public"."issueReports" to "authenticated";

grant select on table "public"."issueReports" to "authenticated";

grant trigger on table "public"."issueReports" to "authenticated";

grant truncate on table "public"."issueReports" to "authenticated";

grant update on table "public"."issueReports" to "authenticated";

grant delete on table "public"."issueReports" to "service_role";

grant insert on table "public"."issueReports" to "service_role";

grant references on table "public"."issueReports" to "service_role";

grant select on table "public"."issueReports" to "service_role";

grant trigger on table "public"."issueReports" to "service_role";

grant truncate on table "public"."issueReports" to "service_role";

grant update on table "public"."issueReports" to "service_role";

grant delete on table "public"."qrCodes" to "anon";

grant insert on table "public"."qrCodes" to "anon";

grant references on table "public"."qrCodes" to "anon";

grant select on table "public"."qrCodes" to "anon";

grant trigger on table "public"."qrCodes" to "anon";

grant truncate on table "public"."qrCodes" to "anon";

grant update on table "public"."qrCodes" to "anon";

grant delete on table "public"."qrCodes" to "authenticated";

grant insert on table "public"."qrCodes" to "authenticated";

grant references on table "public"."qrCodes" to "authenticated";

grant select on table "public"."qrCodes" to "authenticated";

grant trigger on table "public"."qrCodes" to "authenticated";

grant truncate on table "public"."qrCodes" to "authenticated";

grant update on table "public"."qrCodes" to "authenticated";

grant delete on table "public"."qrCodes" to "service_role";

grant insert on table "public"."qrCodes" to "service_role";

grant references on table "public"."qrCodes" to "service_role";

grant select on table "public"."qrCodes" to "service_role";

grant trigger on table "public"."qrCodes" to "service_role";

grant truncate on table "public"."qrCodes" to "service_role";

grant update on table "public"."qrCodes" to "service_role";

grant delete on table "public"."roles" to "anon";

grant insert on table "public"."roles" to "anon";

grant references on table "public"."roles" to "anon";

grant select on table "public"."roles" to "anon";

grant trigger on table "public"."roles" to "anon";

grant truncate on table "public"."roles" to "anon";

grant update on table "public"."roles" to "anon";

grant delete on table "public"."roles" to "authenticated";

grant insert on table "public"."roles" to "authenticated";

grant references on table "public"."roles" to "authenticated";

grant select on table "public"."roles" to "authenticated";

grant trigger on table "public"."roles" to "authenticated";

grant truncate on table "public"."roles" to "authenticated";

grant update on table "public"."roles" to "authenticated";

grant delete on table "public"."roles" to "service_role";

grant insert on table "public"."roles" to "service_role";

grant references on table "public"."roles" to "service_role";

grant select on table "public"."roles" to "service_role";

grant trigger on table "public"."roles" to "service_role";

grant truncate on table "public"."roles" to "service_role";

grant update on table "public"."roles" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


